### ISSUE TITLE
Define API requirements

### ISSUE THREAD

**Issue by joesingo** [joesingo/jasmin-arc-py#2]
Based on the exisiting code in `ceda-arc-app`, the API will need to be able to:
* Submit a job (takes a command and arguments, returns job ID)
* Check job status (takes job ID, returns status)
* Cancel job (takes job ID)
* Save job outputs (takes job ID, returns stdout/stderr/zip file in some form - could be as string, save to path, to `file` object? Should be able to override `outputs_filename` and `errors_filename` in this call)

@agstephens - Anything else?

**Comment by agstephens** [comment]
* Get job outputs....
  - should probably be called "Save job outputs" - it will take the job ID and get the two files that are returned as stderr and stdout. 
    - in tests we have done we are unable to get any other files across (even if they are created in the job session directory on JASMIN). So the limitations are: 
      - stderr file: contains standard error
      - stdout file: we override this by (1) making it into the zip file that contains all the required outputs and (2) the process needs to be careful not the send output to stdout because it can corrupt the zipfile. (Not an ideal solution, but it works).
  - so the action is: download the files and save them to a local path. 

I think that is all

**Comment by joesingo** [comment]
Thanks for replying so quickly

> stdout file: we override this by (1) making it into the zip file that contains all the required outputs and (2) the process needs to be careful not the send output to stdout because it can corrupt the zipfile. (Not an ideal solution, but it works).

I hadn't thought about getting outputs other than std{in,out} - although not sure I completely understand this. How will the library know which files the job has created in order to put them in the zip?

**Comment by agstephens** [comment]
I have experimented with the library and I could only make progress by setting the names of the stderr/out files in the JSDL file. ARC then knows about those files and will allow them to be retrieved to the client. It doesn't matter what you call them but it makes sense to make the stdout file "<something>.zip" so that any processes generating multiple files can be gathered together into that zip file. 

ARC somehow keeps track of the stderr/out files, because they are recovered from this call:

https://github.com/cedadev/ceda-arc-app/blob/master/arcapp/lib/arclib.py#L249

I.e. you don't give the names, they are part of a standard response. Maybe we could get other stuff from that response but I haven't looked in detail.

**Comment by joesingo** [comment]
Okay I think I understand now - so in order to retrieve multiple files the user must make sure their job writes a zip to stdout? Something like
```bash
# do some processing...
zip myzip.zip output1.txt output2.txt
cat myzip.zip
```

**Comment by agstephens** [comment]
A-ha, I understand what you are asking. I've completely confused things (sorry).

On the processing side. You just need to make sure the output is written to a file that has the *same name* as the file specified in the JSDL as being the "stdout" file. E.g.

 * client submits job: stating "stdout file=output.zip"
 * process runs on lotus: writes multiple files and then zips them all into "output.zip" in the job session directory.
 * client will retrieve the stdout file, looking for a file on the LOTUS-side called "output.zip". 
 * when client retrieves the content it can write it to any file name you like.

**Comment by joesingo** [comment]
Thanks Ag, I see now. I was assuming ARC automatically redirected the `std{out,err}` of the job to the files given in the JSDL.

In that case I will not call these files `stdout`/`stderr` in the call to `save_job_outputs()`, as that's what got me so confused in the first place!
